// Derives the site's marks from the two hand-edited drawings in the root,
// logo.svg and piton-favicon.svg. Run by `predev` and `prebuild`, so replacing
// either drawing is all that changing a mark requires.
//
// Three copies exist because three consumers want different things:
//
//   logo.svg        the light-scheme header mark. Starlight takes a path and
//                   renders an <img>, so the ink has to be baked in. No fill
//                   is set on it — SVG's initial fill is black — and that is
//                   left alone here.
//   logo-dark.svg   the same drawing in the dark scheme's ink, for the other
//                   half of Starlight's light/dark image pair.
//   public/logo.svg served at /logo.svg and used as a CSS `mask` by the hero
//                   title, the inline wordmark and the footer mark. A mask
//                   reads alpha only, so this one is a verbatim copy and its
//                   fill is irrelevant.
//
// The favicon is copied the same way, from piton-favicon.svg to
// public/favicon.svg, where Starlight picks it up. Verbatim, because unlike
// the header mark it is a drawing in its own colours — the accent ground with
// the mark reversed out of it — and it has to look the same in a browser tab
// in either scheme, which is exactly what a fixed pair of colours gives.
//
// It also writes the drawing's aspect ratio back into theme.css, where three
// rules size a box from it.
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const read = (p) => readFile(join(root, p), 'utf8');
const write = (p, s) => writeFile(join(root, p), s);

const DARK_INK = '#f4f3ef'; // --pi-ink, dark scheme

const src = await read('logo.svg');

const viewBox = src.match(/viewBox="([\d.\-\s]+)"/)?.[1]?.trim().split(/\s+/);
if (viewBox?.length !== 4) throw new Error('logo.svg: no readable viewBox');
const [, , w, h] = viewBox.map(Number);

// The dark variant recolours by inheritance: `fill` on the root <svg> reaches
// every path that does not set its own, so this survives Inkscape re-exporting
// the drawing as a different number of paths. Explicit blacks are stripped
// first, since those would win over the inherited value.
let dark = src
	.replace(/fill:\s*#0{3,6}\s*;?/gi, '')
	.replace(/\sfill="#0{3,6}"/gi, '');
if (/<svg\b[^>]*\sfill=/.test(dark)) throw new Error('logo.svg: root already sets fill');
dark = dark.replace(/<svg\b/, `<svg\n   fill="${DARK_INK}"`);

// Both outputs are checked in, so they are stamped: a drawing program opening
// one of these and saving over it is the failure this whole script exists to
// prevent, and the banner is the only warning a designer would see.
const stamp = (svg, from) =>
	svg.replace(
		/(<\?xml[^>]*\?>\n?)/,
		`$1<!-- GENERATED by scripts/logo.mjs from ${from}. Do not edit. -->\n`
	);

await mkdir(join(root, 'public'), { recursive: true });
await write('public/logo.svg', stamp(src, 'logo.svg'));
await write('logo-dark.svg', stamp(dark, 'logo.svg'));

const favicon = await read('piton-favicon.svg');
if (!/viewBox="[\d.\-\s]+"/.test(favicon))
	throw new Error('piton-favicon.svg: no readable viewBox');
await write('public/favicon.svg', stamp(favicon, 'piton-favicon.svg'));

// theme.css sizes the masked boxes from the drawing, so the numbers track it.
const css = await read('src/styles/theme.css');
const next = css
	.replace(/(--pi-logo-aspect:\s*)[\d.]+\s*\/\s*[\d.]+/, `$1${w} / ${h}`)
	.replace(/(--pi-logo-ratio:\s*)[\d.]+/, `$1${(w / h).toFixed(4)}`);
if (next !== css) await write('src/styles/theme.css', next);

console.log(`logo: ${w} x ${h} (${(w / h).toFixed(4)}:1) -> public/logo.svg, logo-dark.svg`);
console.log('favicon: piton-favicon.svg -> public/favicon.svg');
