import { defineCollection } from 'astro:content';
import { docsLoader } from '@astrojs/starlight/loaders';
import { docsSchema } from '@astrojs/starlight/schema';
import { examplesDigest } from '../plugins/examples-digest.mjs';
import { renderSpecPages } from '../plugins/spec-pages.mjs';
import { sections } from './config/sections.mjs';
import { readdirSync } from 'node:fs';

type LoaderContext = Parameters<ReturnType<typeof docsLoader>['load']>[0];

/** The project root, where piton.config.pi lives. */
const ROOT = new URL('..', import.meta.url).pathname;

/** Where every page lives, Markdown or Piton. */
const CONTENT = 'src/content/docs/';

/*
 * Starlight's loader, with the examples folded into every entry's digest.
 *
 * Tutorial pages pull their code blocks out of examples/ with `from=` fences
 * (plugins/code-from-file.mjs). The content layer digests the .md file and
 * nothing else, so without this an example edit leaves the cached page
 * untouched and the site rebuilds with the old code in it — the exact drift
 * the includes exist to prevent, just moved into node_modules/.astro.
 *
 * Salting the digest is the whole fix: change any example and every docs entry
 * re-renders.
 */
function docsLoaderWithExamples() {
	const loader = docsLoader();
	const salt = examplesDigest();
	return {
		...loader,
		load: (context: LoaderContext) =>
			loader.load({
				...context,
				generateDigest: (data: Record<string, unknown> | string) =>
					context.generateDigest({ salt, data }),
			}),
	};
}

/*
 * The pages generated from the Piton specification.
 *
 * Each is a .pi file among the Markdown pages in src/content/docs, and its
 * path is its URL the same way: language/values-and-types.pi is served at
 * /language/values-and-types/, and an index.pi is its directory's page.
 * plugins/spec-pages.mjs compiles them against the spec tethered into
 * tethers/piton and writes each page's Markdown. They join the same
 * collection as the hand-written pages, so the sidebar, search, the table of
 * contents and /spec.md treat them exactly alike.
 *
 * In dev, an edit to a page file or to the tethered spec (a `piton update`)
 * re-renders them.
 */
function specPageFiles() {
	const order = (id: string) => {
		const index = sections.flatMap((section) => section.groups).findIndex((group) => id.split('/')[0] === group.directory);
		return index === -1 ? Number.MAX_SAFE_INTEGER : index;
	};
	return (readdirSync(`${ROOT}${CONTENT}`, { recursive: true }) as string[])
		.filter((path) => path.endsWith('.pi'))
		.map((path) => ({
			id: path.replace(/\.pi$/, '').replace(/(^|\/)index$/, ''),
			file: `${ROOT}${CONTENT}${path}`,
			filePath: `${CONTENT}${path}`,
		}))
		.map((page) => ({ ...page, group: order(page.id) }));
}

let specPageIds = new Set<string>();

async function loadSpecPages(context: LoaderContext) {
	const files = specPageFiles();
	const { pages, warnings } = await renderSpecPages({ root: ROOT, files });
	for (const warning of warnings) context.logger.warn(warning);

	// A page file deleted leaves the site with it.
	const ids = new Set(pages.map((page) => page.id));
	for (const id of specPageIds) if (!ids.has(id)) context.store.delete(id);
	specPageIds = ids;

	for (const page of pages) {
		const data = await context.parseData({
			id: page.id,
			data: { title: page.title, description: page.description, sidebar: { order: page.order } },
		});
		const digest = context.generateDigest({ data, body: page.body });
		if (context.store.get(page.id)?.digest === digest) continue;
		// Three things go by the path: Starlight builds the sidebar's
		// autogenerated groups from it, /spec.md finds a group's pages by it,
		// and Starlight's own Markdown plugins — the heading wrappers and
		// anchor links the numbered section bands are styled on, and asides —
		// only run on files under src/content/docs.
		const { filePath } = files.find((file) => file.id === page.id)!;
		context.store.set({
			id: page.id,
			data,
			filePath,
			body: page.body,
			digest,
			rendered: await context.renderMarkdown(page.body, { fileURL: new URL(filePath, `file://${ROOT}`) }),
		});
	}
}

function docsAndSpecLoader() {
	const docs = docsLoaderWithExamples();
	return {
		name: 'docs-and-spec',
		load: async (context: LoaderContext) => {
			await docs.load(context);
			await loadSpecPages(context);

			const sources = [`${ROOT}${CONTENT}`, `${ROOT}src/content/lib`, `${ROOT}tethers`];
			context.watcher?.add(sources);
			context.watcher?.on('all', async (_event, path) => {
				if (!path.endsWith('.pi') || !sources.some((dir) => path.startsWith(dir))) return;
				try {
					await loadSpecPages(context);
				} catch (error) {
					context.logger.error(String(error));
				}
			});
		},
	};
}

export const collections = {
	docs: defineCollection({ loader: docsAndSpecLoader(), schema: docsSchema() }),
};
