import { defineCollection } from 'astro:content';
import { docsLoader } from '@astrojs/starlight/loaders';
import { docsSchema } from '@astrojs/starlight/schema';
import { examplesDigest } from '../plugins/examples-digest.mjs';
import { renderSpecPages } from '../plugins/spec-pages.mjs';

type LoaderContext = Parameters<ReturnType<typeof docsLoader>['load']>[0];

/** The project root, where piton.config.pi lives. */
const ROOT = new URL('..', import.meta.url).pathname;

/*
 * Starlight's loader, with the examples folded into every entry's digest.
 *
 * Tutorial pages pull their code blocks out of examples/ with `from=` fences
 * (plugins/code-from-file.mjs). The content layer digests the .md file and
 * nothing else, so without this an example edit leaves the cached page
 * untouched and the site rebuilds with the old code in it — the exact drift
 * the includes exist to prevent, just moved into node_modules/.astro.
 *
 * Salting the digest is the whole fix: change any example and every docs entry
 * re-renders.
 */
function docsLoaderWithExamples() {
	const loader = docsLoader();
	const salt = examplesDigest();
	return {
		...loader,
		load: (context: LoaderContext) =>
			loader.load({
				...context,
				generateDigest: (data: Record<string, unknown> | string) =>
					context.generateDigest({ salt, data }),
			}),
	};
}

/*
 * The pages generated from the Piton specification.
 *
 * spec/index.pi lists them, and plugins/spec-pages.mjs compiles the spec
 * tethered into tethers/piton and writes each page's Markdown. They join the
 * same collection as the hand-written pages, so the sidebar, search, the
 * table of contents and /spec.md treat them exactly alike.
 *
 * In dev, an edit to the site's Piton source or to the tethered spec (a
 * `piton update`) re-renders them.
 */
let specPageIds = new Set<string>();

async function loadSpecPages(context: LoaderContext) {
	const { pages, warnings } = await renderSpecPages({ root: ROOT });
	for (const warning of warnings) context.logger.warn(warning);

	// A page taken out of spec/ leaves the site with it.
	const ids = new Set(pages.map((page) => page.id));
	for (const id of specPageIds) if (!ids.has(id)) context.store.delete(id);
	specPageIds = ids;

	for (const page of pages) {
		const data = await context.parseData({
			id: page.id,
			data: { title: page.title, description: page.description, sidebar: { order: page.order } },
		});
		const digest = context.generateDigest({ data, body: page.body });
		if (context.store.get(page.id)?.digest === digest) continue;
		context.store.set({
			id: page.id,
			data,
			// Where the page would be if it were written by hand. Starlight
			// builds the sidebar's autogenerated groups from this, and /spec.md
			// finds a group's pages by it; nothing reads the file itself. A
			// slug with no directory is that directory's index page.
			filePath: `src/content/docs/${page.id.includes('/') ? page.id : `${page.id}/index`}.md`,
			body: page.body,
			digest,
			rendered: await context.renderMarkdown(page.body),
		});
	}
}

function docsAndSpecLoader() {
	const docs = docsLoaderWithExamples();
	return {
		name: 'docs-and-spec',
		load: async (context: LoaderContext) => {
			await docs.load(context);
			await loadSpecPages(context);

			const sources = [`${ROOT}spec`, `${ROOT}tethers`];
			context.watcher?.add(sources);
			context.watcher?.on('all', async (_event, path) => {
				if (!path.endsWith('.pi') || !sources.some((dir) => path.startsWith(dir))) return;
				try {
					await loadSpecPages(context);
				} catch (error) {
					context.logger.error(String(error));
				}
			});
		},
	};
}

export const collections = {
	docs: defineCollection({ loader: docsAndSpecLoader(), schema: docsSchema() }),
};
